# MSSQL Database Connection Settings
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FinansDB;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=YourStrong@Password
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
